### ISSUE TITLE
Question for understanding counts output

### ISSUE THREAD

**Issue by Anto007** [AlessioMilanese/read_counter#1]
Hi, 

Many thanks for taking the effort to bring out this very useful tool. I tested it and it ran without issues. I noticed that the counts output (insert.raw_counts) was of fractional nature and not in integers and I'm curious to know the reason for this. I'm aware that Salmon provides a similar output format and the developer stated in one of the issue threads that it's cos the counts are derived from the maximum likelihood estimates. I made a quick search on the web if bwa was doing something like Salmon but couldn't find any clear info. I'm trying to estimate the abundance of a select number of virulence genes across several shotgun metagenomes (Illumina libraries) and I was wondering if you've ever compared read_counter (plus bwa) results to that of Salmon run in the --meta (metagenome) mode to know if the read counts were similar or dissimilar. Thank you again advance for your inputs here.

**Comment by Anto007** [comment]
Also, I presume that rounding off the read_counter raw counts to the nearest integer should be OK for performing differential abundance testing on DESeq2?

**Comment by AlessioMilanese** [comment]
Thanks for your interest.

> I was wondering if you've ever compared read_counter (plus bwa) results to that of Salmon run in the --meta (metagenome) mode to know if the read counts were similar or dissimilar. 

We did not compare to Salmon. But if you do, please let us know!

> I noticed that the counts output (insert.raw_counts) was of fractional nature and not in integers and I'm curious to know the reason for this. 

The absence of integer numbers is due to the presence of multiple mappers. This can lead to situations where you have 12 reads that uniquely map to E. coli, and then 3 reads that map equally well to both E. coli and P. copri. Consequently, we distribute the count of these 3 reads evenly between the two species, resulting in a total count of 13.5 for E. coli.

Have a look also at Figure 3 in this paper for more info on the insert raw counts and other possibilitities:
https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/cpz1.218

**Comment by Anto007** [comment]
Many thanks for your prompt response @AlessioMilanese- much appreciated! Everything is very clear to me and I can let you know later how read_counter results compare to that of Salmon. Just two final questions: in you experience, is it ok to round off the counts before feeding to a DA testing tool and what is the best way to cite the use your tool-GitHub link? or the mOTUs paper?
Thanks a ton again!

**Comment by AlessioMilanese** [comment]
Here's the answers:

> in you experience, is it ok to round off the counts before feeding to a DA testing tool

Yes, I think the `round` would be the best solution. Even tho, sometimes I was using the `floor` function to remove values below 1 (so that 0.87 would become 0), and in theory remove wrong annotaitons. In a way, using `floor` you increase the precision and decrease the recall.

NOTE 1: Normally, in the complete mOTUs pipeline we return integer numbers, but this scripts contain 2/3 of the pipeline.

NOTE 2: If you do a comparison of counts using each gene independently (but under different conditions) like Deseq2, then the insert.raw_counts should work fine. But if you do comparisons between different genes, then you need to use the normalised data (otherwise different gene lengths will bias your analysis).

> what is the best way to cite the use your tool-GitHub link? or the mOTUs paper?

Please cite motus 2 or motus 3. And if you want to be more specific, you can say that you used a github implementation that allow to use only the first 2 (out of 3) steps of the mOTUs pipeline.

**Comment by Anto007** [comment]
Thanks again for your time and your super-useful suggestions
